//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class linqDBContext : DbContext
    {
        public linqDBContext()
            : base("name=linqDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblReseller> tblResellers { get; set; }
        public virtual DbSet<tblItemPicture> tblItemPictures { get; set; }
        public virtual DbSet<tblCC> tblCCs { get; set; }
        public virtual DbSet<tblOrderSummary> tblOrderSummaries { get; set; }
        public virtual DbSet<tblDistributor> tblDistributors { get; set; }
        public virtual DbSet<tblOutlet> tblOutlets { get; set; }
        public virtual DbSet<tblRetail> tblRetails { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWarehouse> tblWarehouses { get; set; }
        public virtual DbSet<tblWholeseller> tblWholesellers { get; set; }
        public virtual DbSet<tblMainCategory> tblMainCategories { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblLot> tblLots { get; set; }
        public virtual DbSet<tblMainInventry> tblMainInventries { get; set; }
        public virtual DbSet<issuedRetailer> issuedRetailers { get; set; }
        public virtual DbSet<tblSubInventory> tblSubInventories { get; set; }
        public virtual DbSet<tblsubInventoryDetail> tblsubInventoryDetails { get; set; }
        public virtual DbSet<tblReturnInventory> tblReturnInventories { get; set; }
        public virtual DbSet<tblreturnHistoryDetail> tblreturnHistoryDetails { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblIssue> tblIssues { get; set; }
        public virtual DbSet<tblReturnHistory> tblReturnHistories { get; set; }
        public virtual DbSet<vInv> vInvs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<tblShare> tblShares { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<Lot_Loose_Items> Lot_Loose_Items { get; set; }
        public virtual DbSet<size> sizes { get; set; }
        public virtual DbSet<Main_Inventory> Main_Inventory { get; set; }
        public virtual DbSet<Main_Inventory_Loose> Main_Inventory_Loose { get; set; }
        public virtual DbSet<Packets_Scale> Packets_Scale { get; set; }
        public virtual DbSet<Lot_Issued> Lot_Issued { get; set; }
        public virtual DbSet<Lot_Issued_Loose> Lot_Issued_Loose { get; set; }
        public virtual DbSet<Inventory_Latest> Inventory_Latest { get; set; }
        public virtual DbSet<Lot_Distributed> Lot_Distributed { get; set; }
        public virtual DbSet<Lot_Distributed_Loose> Lot_Distributed_Loose { get; set; }
        public virtual DbSet<tblItemsSold> tblItemsSolds { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<temp_inv> temp_inv { get; set; }
        public virtual DbSet<temp_issued> temp_issued { get; set; }
        public virtual DbSet<temp_dist> temp_dist { get; set; }
        public virtual DbSet<vDist> vDists { get; set; }
    }
}
