//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Latest
    {
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
        public string size { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> network { get; set; }
        public Nullable<int> localID { get; set; }
    }
}
