//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuedRetailer
    {
        public int Id { get; set; }
        public Nullable<int> retailId { get; set; }
        public Nullable<int> localId { get; set; }
        public string localName { get; set; }
    }
}
