//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot_Distributed
    {
        public int id { get; set; }
        public Nullable<int> issueId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> pacA { get; set; }
        public Nullable<int> pacB { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
