//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCC
    {
        public int id { get; set; }
        public string name { get; set; }
        public string num { get; set; }
        public string expiry { get; set; }
        public string cvc { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
