//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemsSold
    {
        public int id { get; set; }
        public Nullable<int> invoiceNum { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string size { get; set; }
    }
}
