//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutlet
    {
        public int id { get; set; }
        public string OutletName { get; set; }
        public string Phone { get; set; }
        public string Moblie { get; set; }
        public string NTN { get; set; }
        public string Location { get; set; }
        public string OwnerName { get; set; }
        public string NIC { get; set; }
        public string OwnerAddress { get; set; }
        public string ContactNo { get; set; }
        public string UserName { get; set; }
        public string UserMoblieNo { get; set; }
    }
}
