//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderSummary
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> netAmount { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string status { get; set; }
        public string deliveryOption { get; set; }
        public Nullable<decimal> deliveryCharges { get; set; }
        public string payMode { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string shippingAddress { get; set; }
        public string mobile { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
