//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWholeseller
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string NIC { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string NTN { get; set; }
        public string Moblie { get; set; }
        public string ReferredBy { get; set; }
    }
}
