//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ims_mat_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDist
    {
        public string itemCode { get; set; }
        public Nullable<int> pacA { get; set; }
        public Nullable<int> pacB { get; set; }
        public int id { get; set; }
        public Nullable<int> issueId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> K_14 { get; set; }
        public Nullable<int> K_16 { get; set; }
        public Nullable<int> K_18 { get; set; }
        public Nullable<int> K_20 { get; set; }
        public Nullable<int> K_22 { get; set; }
        public Nullable<int> K_24 { get; set; }
        public Nullable<int> K_26 { get; set; }
        public Nullable<int> C28 { get; set; }
        public Nullable<int> K_28 { get; set; }
        public Nullable<int> C30 { get; set; }
        public Nullable<int> C32 { get; set; }
        public Nullable<int> C34 { get; set; }
        public Nullable<int> C36 { get; set; }
        public Nullable<int> C38 { get; set; }
        public Nullable<int> C40 { get; set; }
        public Nullable<int> C42 { get; set; }
        public Nullable<int> C44 { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> XL { get; set; }
        public Nullable<int> XXL { get; set; }
        public Nullable<int> XXXL { get; set; }
    }
}
